version: '3.4'

services:
  honeypot:
    build: .
    container_name: adbhoney
    ports:
      - 5555:5555
    volumes:
      - ./logs:/home/honeypot/logs
      - ./dl:/home/honeypot/dl
      - ./adbhoney.cfg:/etc/adbhoney.cfg
